# Generated by Django 5.0.6 on 2024-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
